stages:
  data_ingestion:
    cmd: python  src/DeepClassifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/DeepClassifier/pipeline/stage_01_data_ingestion.py
      - src/DeepClassifier/components/data_ingestion.py
      - src/DeepClassifier/config/configuration.py
      - src/DeepClassifier/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/DeepClassifier/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/DeepClassifier/components/prepare_base_model.py
      - src/DeepClassifier/pipeline/stage_02_prepare_base_model.py
      - src/DeepClassifier/pipeline/stage_01_data_ingestion.py
      - artifacts/data_ingestion/PetImages
      - src/DeepClassifier/components/data_ingestion.py
      - src/DeepClassifier/config/configuration.py
      - src/DeepClassifier/entity/config_entity.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/DeepClassifier/pipeline/stage_03_training.py
    deps: 
      - src/DeepClassifier/pipeline/stage_03_training.py
      - src/DeepClassifier/components/prepare_callback.py
      - src/DeepClassifier/components/training.py
      - artifacts/prepare_base_model
      - src/DeepClassifier/components/prepare_base_model.py
      - src/DeepClassifier/pipeline/stage_02_prepare_base_model.py
      - src/DeepClassifier/pipeline/stage_01_data_ingestion.py
      - artifacts/data_ingestion/PetImages
      - src/DeepClassifier/components/data_ingestion.py
      - src/DeepClassifier/config/configuration.py
      - src/DeepClassifier/entity/config_entity.py
      - configs/config.yaml
    params:
      - AUGMENTATION
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
    outs:
      - artifacts/training/model.h5
      - artifacts/prepare_callbacks/checkpoint_dir/model.h5
      - artifacts/prepare_callbacks/tensorboard_log_dir